server:
  port: 8081

spring:
  kafka:
    streams:
      application-id: kafka-streams-learning-tasks
      bootstrap-servers: localhost:8097

app:
  kafka-topics:
    topic1-1: task1-1
    topic1-2: task1-2

